import React from 'react'

const rubber_list = [
"Donic Bluestorm Z1 Turbo"
,"Tibhar Aurus TC-1"
,"Xiom Omega VII Tour"
,"DHS Gold Arc 8"
,"Adidas Tenzone Ultra"
,"Andro Rasant Grip"
,"Andro Hexer Powergrip"
,"Gewo Flexxon"
,"DHS Hurricane 3 National (Blue Sponge)"
,"Andro Rasant"
,"Butterfly Dignics 80"
,"Victas VJ > 07 Stiff"
,"Tibhar Nianmor"
,"Xiom Sigma II Euro"
,"Xiom Vega X"
,"Xiom Omega IV Asia"
,"Victas V > 01 Limber"
,"TSP Super Ventus"
,"Yasaka Rakza 7"
,"Victas VS > 402 Double Extra"
,"JOOLA MAXXX-P"
,"Gewo Proton Neo 450"
,"Yasaka Rakza 9"
,"Gewo NanoFlex FT48"
,"Tibhar Evolution MX-S"
,"Adidas P7"
,"Andro Rasanter R50"
,"Tibhar Evolution MX-P 50"
,"Donic Acuda Blue P2"
,"Andro Rasant PowerGrip"
,"Xiom Omega 3 Asian"
,"Butterfly Tenergy 80"
,"Gewo NanoFLEX FT40"
,"Gewo Neoflexx EFT 45"
,"Killerspin Fortissimo"
,"TSP Ventus Spin"
,"Butterfly Tenergy 25 FX"
,"Tibhar Grip-S"
,"DHS Gold Arc 3"
,"Gewo Proton Neo 325"
,"TSP Ventus Soft"
,"Yasaka Mark V HPS"
,"JOOLA Maxxx 500"
,"Yasaka Valmo"
,"Andro Rasant Turbo"
,"DHS Gold Arc 5"
,"Tibhar Aurus Prime"
,"Xiom Sigma 1 Euro"
,"Donic Acuda Blue P1"
,"Andro Plasma Women"
,"Gewo Neoflexx EFT 40"
,"Tibhar Grip-S Europe Soft"
,"Gewo Nexxus EL Pro 50 Hard"
,"Xiom Omega V Asia"
,"JOOLA Rhyzm-P"
,"Tibhar 1Q XD"
,"Gewo Mega Flex Control"
,"Victas V > 01 Stiff"
,"Donic Bluefire M1 Turbo"
,"Gewo Nexxus XT Pro 50 Hard"
,"DHS Hurricane 3 Provincial (No. 22 Blue Sponge)"
,"Tibhar Genius Sound"
,"Xiom Omega IV Pro"
,"Gewo Neoflexx EFT 48"
,"Nittaku Hurricane Pro III Turbo Blue"
,"Gewo Proton Neo 475"
,"DHS NEO Hurricane 3 National (Blue Sponge)"
,"Nittaku Fastarc G-1"
,"Gewo NanoFLEX FT45"
,"Donic J.O. Waldner"
,"Tibhar 5Q Update"
,"Andro Rasanter R53"
,"Tibhar Rapid X-Press"
,"Haifu White Shark II (2) (Tuned)"
,"Xiom Omega IV Euro"
,"Andro Rasanter R47"
,"Andro Rasanter R42"
,"Tibhar 5Q"
,"TSP Regalis Red"
,"Tibhar Evolution EL-P"
,"Tibhar Evolution MX-P"
,"Palio Aeolus"
,"Gewo Proton Neo 375"
,"Yasaka Mark V GPS Soft"
,"Xiom Omega VII Asia"
,"Tibhar Quantum S"
,"Yasaka Xtend HS"
,"Gewo Nexxus EL Pro 43"
,"Butterfly Tenergy 25"
,"Butterfly Tenergy 05 FX"
,"Donic Bluefire JP 03"
,"Victas VS > 401"
,"Stiga Magna TX"
,"Butterfly Tenergy 64"
,"Nittaku Renanos Hold"
,"Gewo Hype KR Pro 47.5"
,"Andro Rasant Powersponge"
,"Butterfly Tenergy 05"
,"Andro Hexer Powergrip SFX"
,"Tibhar Aurus"
]
rubber_list.sort()
let rubber_dict = []
rubber_dict = rubber_list.map(x => ({value: x, label: x}));
//console.log("rubber_dict", rubber_dict)

export default rubber_dict;